In [2]:
type(len)

builtin_function_or_method

In [3]:
import numpy as np

In [10]:
type(np.linspace)

SyntaxError: invalid syntax (252904145.py, line 2)

In [12]:
def my_adder(a, b, c):
    """
    function to sum the 3 numbers
    Input: 3 numbers a, b, c
    Output: the sum of a, b, and c
    author:
    date:
    """
    # this is the summation
    out = a + b + c
    return out
my_adder?

Signature: my_adder(a, b, c)
Docstring:
function to sum the 3 numbers
Input: 3 numbers a, b, c
Output: the sum of a, b, and c
author:
date:
File:      c:\users\user\appdata\local\temp\ipykernel_19628\3190748409.py
Type:      function

In [14]:
def my_trig_sum(a, b):
    """
    function to demo return multiple
    author
    date
    """
    out1 = np.sin(a) + np.cos(b)
    out2 = np.sin(b) + np.cos(a)
    return out1, out2, [out1, out2]
c, d, e = my_trig_sum(2, 3)
print(f"c ={c}, d={d}, e={e}")
c = my_trig_sum(2, 3)
print(f"c={c}, and the returned type is {type(c)}")

c =-0.0806950697747637, d=-0.2750268284872752, e=[-0.0806950697747637, -0.2750268284872752]
c=(-0.0806950697747637, -0.2750268284872752, [-0.0806950697747637, -0.2750268284872752]), and the returned type is <class 'tuple'>


Nested Function

In [15]:
def my_dist_xyz(x, y, z):
    """
    x, y, z are 2D coordinates contained in a tuple
    output:
    d - list, where
    d[0] is the distance between x and y
    d[1] is the distance between x and z
    d[2] is the distance between y and z
    """
    def my_dist(x, y):
        out = np.sqrt((x[0]-y[0])**2+(x[1]-y[1])**2)
        return out
    d0 = my_dist(x, y)
    d1 = my_dist(x, z)
    d2 = my_dist(y, z)
    return [d0, d1, d2]

d = my_dist_xyz((0, 0), (0, 1), (1, 1))
print(d)

[1.0, 1.4142135623730951, 1.0]


Lambda Function

In [16]:
square = lambda x: x**2
print(type(square))
print(square(2))

<class 'function'>
4


In [17]:
my_adder = lambda x, y: x + y
print(my_adder(2, 4))

6


In [18]:
sorted([(1, 2), (2, 0), (4, 1)], key=lambda x: x[1])

[(2, 0), (4, 1), (1, 2)]

In [20]:
def my_fun_plus_one(f, x):
    return f(x) + 1

print(my_fun_plus_one(np.sin, np.pi/2))
print(my_fun_plus_one(np.cos, np.pi/2))
print(my_fun_plus_one(np.sqrt, 25))
print(my_fun_plus_one(lambda x: x + 2, 2))

2.0
1.0
6.0
5


In [21]:
def my_sinh(x):
    return (np.exp(x)-np.exp(-x))/2
print(my_sinh(0),my_sinh(1))

0.0 1.1752011936438014


In [44]:
m=np.eye(5)
print(m.diagonal(1))
m[]=1
print(m)

[0. 0. 0. 0.]
[[1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Comprehension


In [1]:
x = {"a": 1, "b": 2, "c": 3}
y= {key:v**3 for (key, v) in x.items()}
print(y)

{'a': 1, 'b': 8, 'c': 27}
