In [1]:
import numpy as np

In [4]:
arr2D=np.array([[1,4,6],[2,5,7]])
print(arr2D)
print(arr2D.size) #6
print(arr2D.ndim) # 2 dimesion of array
print(arr2D.shape) # 2rows and 3 colums (2,3)

[[1 4 6]
 [2 5 7]]
6
2
(2, 3)


In [7]:
arr1= np.arange(3,6)
arr2 = np.arange(3,9,2)
arr3 = np.arange(1,8,3)
print(arr1,arr2,arr3)

[3 4 5] [3 5 7] [1 4 7]


In [11]:
arr4 = np.ones((2,1))
arr5 = np.zeros((2,2))
arr6 = np.eye(2)
print(arr4)
print(arr5)
print(arr6)
print(arr1[:,np.newaxis])

[[1.]
 [1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]
[[3]
 [4]
 [5]]


In [18]:
print(np.hstack((arr1,arr2)))
print(np.vstack((arr1,arr2)))
print(np.vstack((arr5,arr6)))
print(np.hstack((arr6,arr5)))

[3 4 5 3 5 7]
[[3 4 5]
 [3 5 7]]
[[0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [19]:
arr8 = np.arange(10).reshape((2,5))
print(arr8)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [21]:
print(arr8[0,1:3])
print(arr8[:,4])

[1 2]
[4 9]


In [23]:
arr8_sub = arr8[:,:2]
print(arr8_sub)
arr8_sub[1,1]=1000 # arr8 gets modified as well..
print(arr8)

[[0 1]
 [5 6]]
[[   0    1    2    3    4]
 [   5 1000    7    8    9]]


In [24]:
# To Prevent orignal value. we use copy() method.
arr8_sub2=arr8.copy()
arr8_sub2[1,1]=6
print(arr8)

[[   0    1    2    3    4]
 [   5 1000    7    8    9]]


In [27]:
list1=[1,2,3,4]
list2=[5,6,7,8]
list3=list1+list2
vec1=np.array(list1)
vec2=np.array(list2)
print(vec1+vec2)
print(list1+list2)
vec_distance = np.sqrt(np.sum((vec1 - vec2)**2)) # vec_distance = 8.0
print(vec_distance)

[ 6  8 10 12]
[1, 2, 3, 4, 5, 6, 7, 8]
8.0


In [28]:
arr_sum =arr2D+arr1
print(arr_sum)

[[ 4  8 11]
 [ 5  9 12]]
